all:
	$(CC) $(KERNEL_CFLAGS) -I$(KERNEL_INCLUDE) -c lib.c -o $(OUTDIR)/kernel/lib.o 
	$(CC) $(KERNEL_CFLAGS) -I$(KERNEL_INCLUDE) -c io.c -o $(OUTDIR)/kernel/io.o 
	$(CC) $(KERNEL_CFLAGS) -I$(KERNEL_INCLUDE) -c string.c -o $(OUTDIR)/kernel/string.o 
	
