OUTDIR = ../../../bin/kernel
INCLUDE = ../../kernel

all:
	$(CC) $(KERNEL_CFLAGS) -I$(INCLUDE) -c stdlib.c -o $(OUTDIR)/stdlib.o 
	$(CC) $(KERNEL_CFLAGS) -I$(INCLUDE) -c stdio.c -o $(OUTDIR)/stdio.o 
	
