#!/usr/bin/python3

import sys
import subprocess

if len(sys.argv) < 3:
    print("Too little arguments! Usage: ")
    print(f"    {sys.argv[0]} [kernel_elf_path] [output_file_path]")
    exit(0)

kpath = sys.argv[1]
sympath = sys.argv[2]

syms = []

proc = subprocess.run(["nm", "-P", kpath], capture_output=True)
for line in proc.stdout.decode('utf-8').rstrip().split('\n'):
    elements = line.split()
    if len(elements) < 4:
        syms.append([elements[0], elements[2], '0'])
    else:
        syms.append([elements[0], elements[2], elements[3]])

with open(sympath, "w") as f:
    print(f"# Code generated by {sys.argv[0]}", file=f) 
    print(f"", file=f)
    print(f".section .data", file=f)
    for i, sym in enumerate(syms):
        print(f"name{i}: .asciz \"{sym[0]}\"", file=f) 
    print(f"", file=f)
    print(f".global ksyms, ksyms_len", file=f)
    print(f"ksyms_len: .quad {len(syms)}", file=f)
    print(f"ksyms:", file=f)
    for i, sym in enumerate(syms):
        print(f"    .quad name{i}, 0x{sym[1]}, 0x{sym[2]}", file=f)