#!/usr/bin/python3

import sys
import subprocess
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("input", help="Kernel ELF path")
parser.add_argument("output", help="Output ASM path")
args = parser.parse_args(sys.argv[1:])

kpath = args.input
sympath = args.output

syms = []

proc = subprocess.run(["nm", "-P", kpath], capture_output=True)
for line in proc.stdout.decode('utf-8').rstrip().split('\n'):
    elements = line.split()
    if len(elements) < 4:
        syms.append([elements[0], elements[2], '0'])
    else:
        syms.append([elements[0], elements[2], elements[3]])

with open(sympath, "w") as f:
    print(f"# Code generated by {sys.argv[0]}", file=f) 
    print(f"", file=f)
    print(f".section .data", file=f)
    for i, sym in enumerate(syms):
        print(f"name{i}: .asciz \"{sym[0]}\"", file=f) 
    print(f"", file=f)
    print(f".global ksyms, ksyms_len", file=f)
    print(f"ksyms_len: .quad {len(syms)}", file=f)
    print(f"ksyms:", file=f)
    for i, sym in enumerate(syms):
        print(f"    .quad name{i}, 0x{sym[1]}, 0x{sym[2]}", file=f)